language: cpp

before_install:
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    - sudo apt-get update -qq
    - sudo apt-get install g++-6
    - export CXX="g++-6" CC="gcc-6"

before_script:
  - sudo apt-get install -y xorg-dev libglu1-mesa-dev libudev-dev libjpeg62-dev libsndfile1-dev libglew1.5 libglew1.5-dev libfreetype6 libjpeg-turbo8 libjpeg8 libopenal-data libopenal1 libopenal-dev libxrandr2 libxrender1 libsoil1 libxrandr-dev

script: mkdir build && cd build && cmake .. && make
